const keyArr = [
    {
        id: "Backquote",
        key: "`",
        key2: "0",
        keyCode: "192",
        before: "~",
    },
    {
        id: "Digit1",
        key: "1",
        key2: "1",
        keyCode: "49",
        before: "@",
    },
    {
        id: "Digit2",
        key: "2",
        key2: "2",
        keyCode: "50",
        before: "@",
    },
    {
        id: "Digit3",
        key: "3",
        key2: "3",
        keyCode: "51",
        before: "#",
    },
    {
        id: "Digit4",
        key: "4",
        key2: "4",
        keyCode: "52",
        before: "$",
    },
    {
        id: "Digit5",
        key: "5",
        key2: "5",
        keyCode: "53",
        before: "%",
    },
    {
        id: "Digit6",
        key: "6",
        key2: "6",
        keyCode: "54",
        before: "^",
    },
    {
        id: "Digit7",
        key: "7",
        key2: "7",
        keyCode: "55",
        before: "&",
    },
    {
        id: "Digit8",
        key: "8",
        key2: "8",
        keyCode: "56",
        before: "*",
    },
    {
        id: "Digit9",
        key: "9",
        key2: "9",
        keyCode: "57",
        before: "(",
    },
    {
        id: "Digit0",
        key: "0",
        key2: "0",
        keyCode: "48",
        before: "!",
    },
    {
        id: "Minus",
        key: "-",
        key2: "-",
        keyCode: "189",
        before: "_",
    },
    {
        id: "Equal",
        key: "=",
        key2: "=",
        keyCode: "187",
        before: "+",
    },
    {
        id: "Backspace",
        key: "backspace",
        keyCode: "8",
    },
    {
        id: "Tab",
        key: "Tab",
        key2: "",
        keyCode: "9",
    },
    {
        id: "KeyQ",
        key: "Q",
        key2: "q",
        keyCode: "81",
    },
    {
        id: "KeyW",
        key: "W",
        key2: "w",
        keyCode: "87",
    },
    {
        id: "KeyE",
        key: "E",
        key2: "e",
        keyCode: "69",
    },
    {
        id: "KeyR",
        key: "R",
        key2: "r",
        keyCode: "82",
    },
    {
        id: "KeyT",
        key: "T",
        key2: "t",
        keyCode: "84",
    },
    {
        id: "KeyY",
        key: "Y",
        key2: "y",
        keyCode: "89",
    },
    {
        id: "KeyU",
        key: "U",
        key2: "u",
        keyCode: "85",
    },
    {
        id: "KeyI",
        key: "I",
        key2: "i",
        keyCode: "73",
    },
    {
        id: "KeyO",
        key: "O",
        key2: "o",
        keyCode: "79",
    },
    {
        id: "KeyP",
        key: "P",
        key2: "p",
        keyCode: "80",
    },
    {
        id: "BracketLeft",
        key: "[",
        key2: "{",
        keyCode: "219",
    },
    {
        id: "BracketRight",
        key: "]",
        key2: "}",
        keyCode: "221",
    },
    {
        id: "Backslash",
        key: "\\",
        key2: "|",
        keyCode: "220",
    },
    {
        id: "Delete",
        key: "Del",
        keyCode: "46",
    },
];
