const keyArr = [
    {
        id: "Backquote",
        key: "`",
        key2: "~",
        keyCode: "192",
    },
    {
        id: "Digit1",
        key: "1",
        key2: "!",
        keyCode: "49",
    },
    {
        id: "Digit2",
        key: "2",
        key2: "@",
        keyCode: "50",
    },
    {
        id: "Digit3",
        key: "3",
        key2: "#",
        keyCode: "51",
    },
    {
        id: "Digit4",
        key: "4",
        key2: "$",
        keyCode: "52",
    },
    {
        id: "Digit5",
        key: "5",
        key2: "%",
        keyCode: "53",
    },
    {
        id: "Digit6",
        key: "6",
        key2: "^",
        keyCode: "54",
    },
    {
        id: "Digit7",
        key: "7",
        key2: "&",
        keyCode: "55",
    },
    {
        id: "Digit8",
        key: "8",
        key2: "*",
        keyCode: "56",
    },
    {
        id: "Digit9",
        key: "9",
        key2: "(",
        keyCode: "57",
    },
    {
        id: "Digit0",
        key: "0",
        key2: "!",
        keyCode: "48",
    },
    {
        id: "Minus",
        key: "-",
        key2: "_",
        keyCode: "189",
    },
    {
        id: "Equal",
        key: "=",
        key2: "+",
        keyCode: "187",
    },
    {
        id: "Backspace",
        key: "Backspace",
        keyCode: "8",
    },
    {
        id: "Tab",
        key: "Tab",
        keyCode: "9",
        textContent: "Tab",
    },
    {
        id: "KeyQ",
        key: "Q",
        keyCode: "81",
    },
    {
        id: "KeyW",
        key: "W",
        keyCode: "87",
    },
    {
        id: "KeyE",
        key: "E",
        keyCode: "69",
    },
    {
        id: "KeyR",
        key: "R",
        keyCode: "82",
    },
    {
        id: "KeyT",
        key: "T",
        key2: "t",
        keyCode: "84",
    },
    {
        id: "KeyY",
        key: "Y",
        keyCode: "89",
    },
    {
        id: "KeyU",
        key: "U",
        keyCode: "85",
    },
    {
        id: "KeyI",
        key: "I",
        keyCode: "73",
    },
    {
        id: "KeyO",
        key: "O",
        keyCode: "79",
    },
    {
        id: "KeyP",
        key: "P",
        keyCode: "80",
    },
    {
        id: "BracketLeft",
        key: "[",
        key2: "{",
        keyCode: "219",
    },
    {
        id: "BracketRight",
        key: "]",
        key2: "}",
        keyCode: "221",
    },
    {
        id: "Backslash",
        key: "\\",
        key2: "|",
        keyCode: "220",
    },
    {
        id: "Delete",
        key: "Del",
        keyCode: "46",
    },
    {
        id: "CapsLock",
        key: "CapsLock",
        keyCode: "20",
    },
    {
        id: "KeyA",
        key: "A",
        keyCode: "65",
    },
    {
        id: "KeyS",
        key: "S",
        keyCode: "83",
    },
    {
        id: "KeyD",
        key: "D",
        keyCode: "68",
    },
    {
        id: "KeyF",
        key: "F",
        keyCode: "70",
    },
    {
        id: "KeyG",
        key: "G",
        keyCode: "71",
    },
    {
        id: "KeyH",
        key: "H",
        keyCode: "72",
    },
    {
        id: "KeyJ",
        key: "J",
        keyCode: "74",
    },
    {
        id: "KeyK",
        key: "K",
        keyCode: "75",
    },
    {
        id: "KeyL",
        key: "L",
        keyCode: "76",
    },
    {
        id: "Semicolon",
        key: ";",
        key2: ":",
        keyCode: "186",
    },
    {
        id: "Quote",
        key: "'",
        key2: '"',
        keyCode: "222",
    },
    {
        id: "Enter",
        key: "Enter",
        key2: "Enter",
        keyCode: "13",
    },
    {
        id: "ShiftLeft",
        key: "Shift",
        keyCode: "16",
    },
   
    {
        id: "KeyZ",
        key: "Z",
        keyCode: "90",
    },
    {
        id: "KeyX",
        key: "X",
        keyCode: "88",
    },
    {
        id: "KeyC",
        key: "C",
        keyCode: "67",
    },
    {
        id: "KeyV",
        key: "V",
        keyCode: "86",
    },
    {
        id: "KeyB",
        key: "B",
        keyCode: "66",
    },
    {
        id: "KeyN",
        key: "N",
        keyCode: "78",
    },
    {
        id: "KeyM",
        key: "M",
        keyCode: "77",
    },
    {
        id: "Comma",
        key: ",",
        key2: "<",
        keyCode: "188",
    },
    {
        id: "Period",
        key: ".",
        key2: ">",
        keyCode: "190",
    },
    {
        id: "Slash",
        key: "/",
        key2: "?",
        keyCode: "191",
    },
    {
        id: "ArrowUp",
        key: "ArrowUp",
        keyCode: "38",
        textContent: "↑",
    },
    {
        id: "ShiftRight",
        key: "Shift",
        keyCode: "16",
        textContent: "Shift",
    },
    {
        id: "ControlLeft",
        key: "Control",
        keyCode: "17",
        textContent: "Ctrl",
    },
    {
        id: "Win",
        key: "Win",
        keyCode: "91",
        textContent: "Win",
    },
    {
        id: "AltLeft",
        key: "Alt",
        keyCode: "18",
        textContent: "Alt",
        
    },
    {
        id: "Space",
        key: "Space",
        keyCode: "32",
        textContent: "Space",
    },
    {
        id: "AltRight",
        key: "Alt",
        keyCode: "18",
        textContent: "Alt",
    },
    {
        id: "ControlRight",
        key: "Control",
        keyCode: "17",
        textContent: "Ctrl",
    },
    {
        id: "ArrowLeft",
        key: "ArrowLeft",
        keyCode: "37",
        textContent: "←",
    },
    {
        id: "ArrowDown",
        key: "ArrowDown",
        keyCode: "40",
        textContent: "↓",
    },
    {
        id: "ArrowRight",
        key: "→",
        keyCode: "39",
        textContent: "qqq",
    },
];
